name: irri
description: Third party, modern support for the Hydrawise API
version: 0.0.28+31
publish_to: none

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  api_models:
    git:
      url: https://github.com/btrautmann/irri-models.git
      ref: main
  clock: ^1.1.0
  collection: ^1.15.0
  core:
    path: ../core
  core_ui:
    path: ../core_ui
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  go_router: ^3.0.4
  gooder_store: ^0.0.1-dev.2
  google_fonts: ^2.1.0
  hooks_riverpod: ^2.0.0-dev.9
  provider: ^6.0.0
  rx_shared_preferences: ^3.0.0
  shared_preferences: ^2.0.13
  simple_animations: ^5.0.0+2
  tab_indicator_styler: ^2.0.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true
