name: irri
description: Third party, modern support for the Hydrawise API
version: 0.0.28+31
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  bloc: ^8.0.3
  clock: ^1.1.0
  cloud_firestore: ^3.1.0
  collection: ^1.15.0
  core:
    path: ../core
  core_ui:
    path: ../core_ui
  dio: ^4.0.6
  equatable: ^2.0.3
  firebase_analytics: ^9.1.2
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1
  firebase_crashlytics: ^2.2.4
  firebase_messaging: ^11.2.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_native_timezone: ^2.0.0
  freezed_annotation: ^2.0.3
  go_router: ^3.0.4
  google_fonts: ^2.1.0
  http: ^0.13.3
  hydrawise:
    path: ../hydrawise
  intl: ^0.17.0
  path: ^1.8.0
  pedantic: ^1.11.1
  provider: ^6.0.0
  result_type: ^0.1.0
  shared_preferences: ^2.0.13
  uuid: ^3.0.5
  weatherx:
    path: ../weather

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.2
  charlatan: ^0.1.0
  fake_cloud_firestore: ^1.2.0
  firebase_auth_mocks: ^0.8.1
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^2.0.4
  json_serializable: ^6.1.4
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
