name: weatherx
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  bloc: ^8.0.3
  core:
    path: ../core
  core_ui:
    path: ../core_ui
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.0.3
  result_type: ^0.1.0
  weather: ^2.0.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.5

flutter: