include: package:flutter_lints/flutter.yaml
analyzer:
  exclude: ['**.freezed.dart', '**.g.dart']
  errors:
    # Don't flag TODOs - comment this out when wanting to address
    todo: ignore
    sized_box_for_whitespace: error
    avoid_print: error
linter:
  rules:
    sort_constructors_first: true
    public_member_api_docs: false
    directives_ordering: true
    