include: package:flutter_lints/flutter.yaml
analyzer:
  exclude: ['**.freezed.dart', '**.g.dart']
  errors:
    # Don't flag TODOs - comment this out when wanting to address
    todo: ignore
linter:
  rules:
    public_member_api_docs: false
