name: hydrawise
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  bloc: ^7.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^0.14.2
  google_fonts: ^2.1.0
  http: ^0.13.3
  intl: ^0.17.0
  path: ^1.8.0
  provider: ^6.0.0
  shared_preferences: ^2.0.7
  sqflite: ^2.0.0+4
  weather: ^2.0.1

dev_dependencies:
  bloc_test: ^8.1.0
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  json_serializable: ^4.1.0
  mocktail: ^0.1.0
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
  generate: true
