name: hydrawise
description: A Very Good Project created by Very Good CLI.
version: 0.0.16+19
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  bloc: ^7.1.0
  cloud_firestore: ^3.1.0
  dio: ^4.0.0
  firebase_analytics: ^8.3.4
  firebase_auth: ^3.2.0
  firebase_core: ^1.8.0
  firebase_crashlytics: ^2.2.4
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^0.14.2
  go_router: ^2.1.2
  google_fonts: ^2.1.0
  http: ^0.13.3
  intl: ^0.17.0
  path: ^1.8.0
  pedantic: ^1.11.1
  provider: ^6.0.0
  result_type: ^0.1.0
  shared_preferences: ^2.0.7
  sqflite: ^2.0.0+4
  uuid: ^3.0.5
  weather: ^2.0.1

dev_dependencies:
  bloc_test: ^8.1.0
  build_runner: ^2.1.2
  fake_cloud_firestore: ^1.2.0
  firebase_auth_mocks: ^0.8.1
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  json_serializable: ^4.1.0
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
