name: core
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=2.16.2 <3.0.0'


dependencies:
  dio: ^4.0.6
  result_type: ^0.1.0
  shared_preferences: ^2.0.13


dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
