name: core
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  dio: ^4.0.6
  result_type: ^0.1.0
  rx_shared_preferences: ^3.0.0


dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
