name: api_wrapper
description: A server app using the shelf package and Docker.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  api_models:
    path: ../api_models
  args: ^2.0.0
  dotenv: ^4.0.1
  http: ^0.13.4
  hydrawise:
    git:
      url: https://github.com/btrautmann/hydrawise-models.git
      ref: 97e2adafc2f095f2697bdcdc5bb997ec506465be
  postgres: ^2.4.5
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  uuid: ^3.0.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.15.0
