name: api_wrapper
description: A server app using the shelf package and Docker.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  api_models:
    path: /Users/brandontrautmann/Development/irri-models
  args: ^2.0.0
  collection: ^1.17.1
  dotenv: ^4.0.1
  http: ^0.13.4
  hydrawise: ^0.0.1
  postgres: ^2.4.5
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  slack_notifier: ^1.2.0
  timezone: ^0.8.0
  uuid: ^3.0.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.15.0
