# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

open_weather_map_api_key = ENV["OPEN_WEATHER_MAP_API_KEY"]

platform :ios do
  desc "Deploy a new version to Test Flight"
  lane :deploy do
    version_name = ENV["VERSION_NAME"]
    build_number = ENV["BUILD_NUMBER"]
    base_url = ENV["BASE_URL"]

    setup_ci

    match(
      type: "appstore",
      readonly: true
    )
    app_store_connect_api_key(
      is_key_content_base64: true,
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )
    sh("flutter", "packages", "get")
    cocoapods(
      clean_install: true,
      podfile: "./Podfile"
    )
    mapping_path = File.absolute_path("../export_options.plist")
    sh(
      "flutter",
      "build",
      "ipa",
      "--build-number=#{build_number}",
      "--build-name=#{version_name}",
      "--dart-define=OPEN_WEATHER_MAP_API_KEY=#{open_weather_map_api_key}",
      "--dart-define=BASE_URL=#{base_url}",
      "--export-options-plist=#{mapping_path}",
      "-v"
    )
    upload_to_testflight(
      ipa: "../build/ios/ipa/Hydrawise.ipa",
      skip_waiting_for_build_processing: true
    )
  end
end
