name: api_models
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  freezed_annotation: ^2.0.3

dev_dependencies:
  build_runner: ^2.1.2
  freezed: ^2.0.5
  json_serializable: ^6.1.4
  lints: ^1.0.0
  test: ^1.16.0
