# frozen_string_literal: true

source 'https://rubygems.org'

gem 'google-cloud-tasks', '~>2.1'
gem 'sinatra', '~>3.0'
# Required to use some advanced features of# Sinatra, like namespaces
gem 'sinatra-contrib'

group :test do
  gem 'rack-test'
  gem 'rest-client'
  gem 'rspec'
  gem 'rspec_junit_formatter'
  gem 'rspec-retry'
  gem 'rubysl-securerandom'
end
