source 'https://rubygems.org'

gem 'google-cloud-tasks', '~>2.1'
gem 'sinatra', '~>2.0'
# Required to use some advanced features of# Sinatra, like namespaces
gem 'sinatra-contrib'
# https://stackoverflow.com/questions/67615800/ruby-sinatra-compile-error-server-handler-thin-puma-reel-http-webrick-not-fo
gem 'thin'
gem 'puma'
gem 'reel'
gem 'http'
gem 'webrick'

group :test do
  gem 'rack-test'
  gem 'rest-client'
  gem 'rspec'
  gem 'rspec_junit_formatter'
  gem 'rspec-retry'
  gem 'rubysl-securerandom'
end
