# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

open_weather_map_api_key = ENV["OPEN_WEATHER_MAP_API_KEY"]

platform :ios do
  desc "Deploy a new version to Test Flight"
  lane :deploy do
    sh("flutter", "clean")
    sh("flutter", "packages", "get")
    cocoapods(
      clean_install: true,
      podfile: "./Podfile"
    )
    sh("flutter", "build", "ios", "-dart-define=OPEN_WEATHER_MAP_API_KEY=#{open_weather_map_api_key}", "--flavor=production", "--target=lib/main_production.dart", "--no-codesign", "-v")
    match(
      type: "appstore",
      git_basic_authorization: ENV["BASIC_AUTH_HEADER"],
      keychain_password: ENV["MATCH_PASSWORD"],
      readonly: true)
    upload_to_testflight
  end
end
