# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Deploy a new version to Test Flight"
  lane :deploy do
    cocoapods(
      clean_install: true,
      podfile: "./Podfile"
    )
    sh("flutter", "build", "appbundle", "-dart-define=OPEN_WEATHER_MAP_API_KEY=#{open_weather_map_api_key}", "--flavor=production", "--target=lib/main_production.dart", "-v")
    match(
      type: "appstore",
      git_basic_authorization: ENV["BASIC_AUTH_HEADER"]
      keychain_password: ENV["MATCH_PASSWORD"]
      readonly: true)
  end
end
