name: hydrawise
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  bloc: ^8.0.3
  clock: ^1.1.0
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.0.3

dev_dependencies:
  build_runner: ^2.1.8
  freezed: ^2.0.5
  json_serializable: ^6.1.4
  lints: ^1.0.0
  test: ^1.16.0
