# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

open_weather_map_api_key = ENV["OPEN_WEATHER_MAP_API_KEY"]
json_key_data = ENV["ANDROID_SECRET_JSON_FILE"]


platform :android do
  desc "Deploy a new version to the Google Play"
  lane :deploy do
    Dir.chdir "android" do
      sh("flutter", "clean")
      sh("flutter", "packages", "get")
      sh("flutter", "build", "appbundle", "-dart-define=#{open_weather_map_api_key}", "--flavor=production", "--target=lib/main_production.dart")
    end
    
    upload_to_play_store(
      track: "beta",
      aab: "build/app/outputs/bundle/productionRelease/app-production-release.aab",
      skip_upload_screenshots: true,
      skip_upload_images: true
      json_key_data: "#{json_key_data}"
    )

  end
end
