name: Run code coverage
on:
  pull_request:
    branches:
      - main
    paths:
      - mobile/**
  push:
    branches:
      - main
    paths:
      - mobile/**
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_code_coverage:
    runs-on: ubuntu-latest
    env:
      FLUTTER_BUILD_CHANNEL: stable
      FLUTTER_BUILD_VERSION: 3.0.4

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v1.5.3
        with:
          channel: ${{ env.FLUTTER_BUILD_CHANNEL }}
          flutter-version: ${{ env.FLUTTER_BUILD_VERSION }}
          
      - name: Install remove_from_coverage
        run: dart pub global activate remove_from_coverage

      - name: Run code coverage
        run: flutter test --coverage --test-randomize-ordering-seed random lib
        working-directory: mobile/app
        
      - name: Remove generated files
        run: remove_from_coverage -f coverage/lcov.info -r '\.g\.dart$' && remove_from_coverage -f coverage/lcov.info -r '\.freezed\.dart$'
        working-directory: mobile/app

      - uses: codecov/codecov-action@v2
        with:
          files: mobile/app/coverage/lcov.info

