name: main push

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-mobile:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
     
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.2'
          channel: stable

      - name: Build Flutter Android
        run: flutter build appbundle --flavor=production --target=lib/main_production.dart

      - name: Sign Android
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: build/app/outputs/bundle/productionRelease/
          signingKeyBase64: ${{ secrets.ANDROID_UPLOAD_KEYSTORE_FILE }}
          alias: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD }}

      - name: Release Android
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.brandontrautmann.hydrawise_companion
          releaseFiles: build/app/outputs/bundle/productionRelease/*.aab
          track: beta
          mappingFile: build/app/outputs/mapping/production/release/mapping.txt