name: mobile verification

on:
  pull_request:
    branches:
      - main
    paths:
      - mobile/**

jobs:
  verify:
    defaults:
      run:
        working-directory: mobile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{secrets.SSH_PRIVATE_KEY}}
      - uses: subosito/flutter-action@v2.4.0
        with:
          flutter-version: '3.7.0'
          channel: stable
      - run: dart pub global activate melos 2.9.0 && melos bs
      - run: melos exec --flutter -- flutter analyze
      - run: melos exec --no-flutter -- dart analyze
