name: mobile verification

on:
  pull_request:
    branches:
      - main
    paths:
      - mobile/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  verify:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{secrets.SSH_PRIVATE_KEY}}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.3'
          channel: stable
          
      - name: activate melos
        run: dart pub global activate melos && cd mobile && melos bs
            
      - name: verify flutter
        run: cd mobile && melos exec -- flutter test --test-randomize-ordering-seed random && flutter analyze
