name: main pull request

on:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  verify:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{secrets.SSH_PRIVATE_KEY}}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.3'
          channel: stable
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      
      - name: verify flutter
        run: cd mobile && flutter test && flutter analyze
