name: main push

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-mobile:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{secrets.SSH_PRIVATE_KEY}}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.2'
          channel: stable
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      
      - name: Bundle install
        run: bundle install

      # - name: Decode keystore file
      #   run: echo "${{secrets.ANDROID_UPLOAD_KEYSTORE_FILE}}" | base64 --decode > ${{secrets.ANDROID_KEYSTORE_PATH}}
      #   working-directory: android/app  

      # - name: Deploy Android to Beta
      #   env:
      #     ANDROID_KEYSTORE_PATH: ${{secrets.ANDROID_KEYSTORE_PATH}}
      #     ANDROID_KEYSTORE_ALIAS: ${{secrets.ANDROID_KEYSTORE_ALIAS}}
      #     ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD: ${{secrets.ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD}}
      #     ANDROID_KEYSTORE_PASSWORD: ${{secrets.ANDROID_KEYSTORE_PASSWORD}}
      #     ANDROID_SECRET_JSON_FILE: ${{secrets.ANDROID_SECRET_JSON_FILE}}
      #     OPEN_WEATHER_MAP_API_KEY: ${{secrets.OPEN_WEATHER_MAP_API_KEY}}
      #   run: cd android && bundle exec fastlane deploy

      - name: Create iOS p8 file
        run: echo "${{secrets.APP_STORE_CONNECT_API_KEY}}" > ./app_store_api_key.p8 && ls

      - name: Deploy iOS to TestFlight
        env:
          MATCH_PASSWORD: ${{secrets.MATCH_PASSWORD}}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{secrets.BASIC_AUTH_HEADER}}
          OPEN_WEATHER_MAP_API_KEY: ${{secrets.OPEN_WEATHER_MAP_API_KEY}}
          APP_STORE_CONNECT_API_KEY_ID: ${{secrets.APP_STORE_CONNECT_API_KEY_ID}}
          APP_STORE_CONNECT_API_KEY_ISSUER: ${{secrets.APP_STORE_CONNECT_API_KEY_ISSUER}}
        run: cd ios && bundle exec fastlane deploy