name: main push

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-mobile:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
     
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.2'
          channel: stable
          
      - name: Setup Fastlane
        run: bundle install

      - name: Decode keystore file
        run: echo "$ANDROID_UPLOAD_KEYSTORE_FILE" | base64 --decode > ~/hc-upload-keystore.jks

      - name: Deploy Android
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
      - uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'deploy'
          subdirectory: 'android'